import React from "react";

export default function Component() {
  return (
    <>
      <header
        style={{
          boxSizing: "inherit",
          outline: "0px",
          backgroundColor: "rgb(255, 248, 229)",
          overflow: "hidden",
          paddingTop: "130px",
          position: "relative",
          zIndex: 9,
        }}
      >
        <div
          className="un-container"
          style={{
            boxSizing: "inherit",
            outline: "0px",
            margin: "0px auto",
            width: "auto",
            maxWidth: "1180px",
            display: "flex",
          }}
        >
          <div
            className="cptn"
            style={{ boxSizing: "inherit", outline: "0px", width: "550px" }}
          >
            <h1
              className="h1_medium"
              style={{
                boxSizing: "inherit",
                outline: "0px",
                marginTop: "0px",
                color: "#383838",
                fontSize: "48px",
                fontWeight: 500,
                lineHeight: "61px",
                position: "relative",
                marginBottom: "40px",
              }}
            >
              {" "}
              How can we help you?{" "}
            </h1>
            <p
              className="p_large"
              style={{
                boxSizing: "inherit",
                outline: "0px",
                marginTop: "0px",
                fontWeight: 400,
                lineHeight: "140%",
                color: "#383838",
                fontSize: "16px",
                marginBottom: "30px",
              }}
            >
              {" "}
              Thank you for showing your interest in collaborating and
              interacting with us. Our hardworking and dedicated team is ready
              to help you in every possible way.{" "}
            </p>
            <button
              className="un-button waves-effect large"
              style={{
                colorScheme: "",
                forcedColorAdjust: "",
                mask: "unset",
                mathDepth: "",
                positionAnchor: "",
                textSizeAdjust: "",
                appearance: "",
                fontFamily: "",
                fontFeatureSettings: "",
                fontKerning: "",
                fontOpticalSizing: "",
                fontPalette: "",
                fontSizeAdjust: "",
                fontStretch: "",
                fontStyle: "",
                fontSynthesis: "unset",
                fontVariant: "unset",
                fontVariationSettings: "",
                positionArea: "",
                textOrientation: "",
                textRendering: "",
                textSpacingTrim: "",
                WebkitFontSmoothing: "",
                WebkitLocale: "",
                WebkitTextOrientation: "",
                WebkitWritingMode: "",
                writingMode: "",
                zoom: null,
                accentColor: "",
                alignContent: "",
                placeSelf: "unset",
                alignmentBaseline: "",
                anchorName: "",
                anchorScope: "",
                animationComposition: "",
                animation: "unset",
                appRegion: "",
                aspectRatio: "",
                backdropFilter: "",
                backfaceVisibility: "",
                backgroundBlendMode: "",
                baselineShift: "",
                baselineSource: "",
                blockSize: "",
                borderBlock: "unset",
                border: "0px",
                borderRadius: "8px",
                borderCollapse: "",
                borderEndEndRadius: "",
                borderEndStartRadius: "",
                borderInline: "unset",
                borderStartEndRadius: "",
                borderStartStartRadius: "",
                inset: "unset",
                boxDecorationBreak: "",
                boxShadow: "",
                breakAfter: "",
                breakBefore: "",
                breakInside: "",
                bufferedRendering: "",
                captionSide: "",
                caretColor: "",
                clear: "",
                clip: "",
                clipPath: "",
                clipRule: "",
                colorInterpolation: "",
                colorInterpolationFilters: "",
                colorRendering: "",
                columns: "unset",
                columnFill: "",
                gap: "unset",
                columnRule: "unset",
                columnSpan: "",
                contain: "",
                containIntrinsicBlockSize: "",
                containIntrinsicSize: "unset",
                containIntrinsicInlineSize: "",
                container: "unset",
                content: "",
                contentVisibility: "",
                counterIncrement: "",
                counterReset: "",
                counterSet: "",
                cx: "",
                cy: "",
                d: "",
                dominantBaseline: "",
                emptyCells: "",
                fieldSizing: "",
                fill: "",
                fillOpacity: null,
                fillRule: "",
                filter: "",
                flexBasis: "",
                flexFlow: "unset",
                flexGrow: null,
                cssFloat: "",
                floodColor: "",
                floodOpacity: "",
                grid: "unset",
                gridArea: "unset",
                hyphenateCharacter: "",
                hyphenateLimitChars: "",
                hyphens: "",
                imageOrientation: "",
                imageRendering: "",
                initialLetter: "",
                inlineSize: "",
                insetBlock: "unset",
                insetInline: "unset",
                interpolateSize: "",
                isolation: "",
                justifyItems: "",
                letterSpacing: "",
                lightingColor: "",
                lineBreak: "",
                listStyle: "unset",
                marginBlock: "unset",
                margin: "unset",
                marginInline: "unset",
                marker: "unset",
                maskType: "",
                mathShift: "",
                mathStyle: "",
                maxBlockSize: "",
                maxHeight: "",
                maxInlineSize: "",
                maxWidth: "",
                minBlockSize: "",
                minHeight: "",
                minInlineSize: "",
                minWidth: "",
                mixBlendMode: "",
                objectFit: "",
                objectPosition: "",
                objectViewBox: "",
                offset: "unset",
                opacity: null,
                order: null,
                orphans: null,
                outline: "unset",
                outlineOffset: "",
                overflowAnchor: "",
                overflowClipMargin: "",
                overflowWrap: "",
                overlay: "",
                overscrollBehaviorBlock: "",
                overscrollBehaviorInline: "",
                overscrollBehavior: "unset",
                paddingBlock: "unset",
                padding: "unset",
                paddingInline: "unset",
                page: "",
                pageOrientation: "",
                paintOrder: "",
                perspective: "",
                perspectiveOrigin: "",
                pointerEvents: "",
                positionTry: "unset",
                positionVisibility: "",
                quotes: "",
                r: "",
                resize: "",
                rotate: "",
                rubyAlign: "",
                rubyPosition: "",
                rx: "",
                ry: "",
                scale: "",
                scrollBehavior: "",
                scrollMarginBlock: "unset",
                scrollMargin: "unset",
                scrollMarginInline: "unset",
                scrollPaddingBlock: "unset",
                scrollPadding: "unset",
                scrollPaddingInline: "unset",
                scrollSnapAlign: "",
                scrollSnapStop: "",
                scrollSnapType: "",
                scrollTimeline: "unset",
                scrollbarColor: "",
                scrollbarGutter: "",
                scrollbarWidth: "",
                shapeImageThreshold: "",
                shapeMargin: "",
                shapeOutside: "",
                shapeRendering: "",
                size: "",
                speak: "",
                stopColor: "",
                stopOpacity: "",
                stroke: "",
                strokeDasharray: "",
                strokeDashoffset: null,
                strokeLinecap: "",
                strokeLinejoin: "",
                strokeMiterlimit: "",
                strokeOpacity: null,
                strokeWidth: null,
                tabSize: null,
                tableLayout: "",
                textAlign: "",
                textAlignLast: "",
                textAnchor: "",
                textCombineUpright: "",
                textDecoration: "unset",
                textDecorationSkipInk: "",
                textEmphasis: "unset",
                textEmphasisPosition: "",
                textIndent: "",
                textOverflow: "",
                textShadow: "",
                textTransform: "",
                textUnderlineOffset: "",
                textUnderlinePosition: "",
                whiteSpace: "nowrap",
                textWrapStyle: "",
                timelineScope: "",
                touchAction: "",
                transform: "",
                transformBox: "",
                transformOrigin: "",
                transformStyle: "",
                translate: "",
                userSelect: "",
                vectorEffect: "",
                verticalAlign: "",
                viewTimeline: "unset",
                viewTransitionClass: "",
                viewTransitionName: "",
                visibility: "",
                borderSpacing: "unset",
                WebkitBoxAlign: "",
                WebkitBoxDecorationBreak: "",
                WebkitBoxDirection: "",
                WebkitBoxFlex: "",
                WebkitBoxOrdinalGroup: "",
                WebkitBoxOrient: "",
                WebkitBoxPack: "",
                WebkitBoxReflect: "",
                WebkitLineBreak: "",
                WebkitLineClamp: "",
                WebkitMaskBoxImage: "unset",
                WebkitPrintColorAdjust: "",
                WebkitRtlOrdering: "",
                WebkitRubyPosition: "",
                WebkitTapHighlightColor: "",
                WebkitTextCombine: "",
                WebkitTextDecorationsInEffect: "",
                WebkitTextFillColor: "",
                WebkitTextSecurity: "",
                WebkitTextStroke: "unset",
                WebkitUserDrag: "",
                widows: null,
                width: "",
                willChange: "",
                wordBreak: "",
                wordSpacing: "",
                x: "",
                y: "",
                boxSizing: "border-box",
                display: "inline-flex",
                justifyContent: "center",
                alignItems: "center",
                fontWeight: 400,
                flexShrink: 0,
                height: "48px",
                fontSize: "16px",
                lineHeight: "19px",
                transition: "0.3s",
                overflow: "hidden",
                position: "relative",
                zIndex: 9,
                cursor: "pointer",
                background: "#0073E6",
                color: "#FFFFFF",
              }}
            >
              <span
                className="un-icon-container ng-star-inserted"
                style={{
                  colorScheme: "",
                  forcedColorAdjust: "",
                  mask: "unset",
                  mathDepth: "",
                  position: "",
                  positionAnchor: "",
                  textSizeAdjust: "",
                  appearance: "",
                  color: "",
                  font: "unset",
                  fontPalette: "",
                  fontSynthesis: "unset",
                  positionArea: "",
                  textOrientation: "",
                  textRendering: "",
                  textSpacingTrim: "",
                  WebkitFontSmoothing: "",
                  WebkitLocale: "",
                  WebkitTextOrientation: "",
                  WebkitWritingMode: "",
                  writingMode: "",
                  zoom: null,
                  accentColor: "",
                  placeContent: "unset",
                  placeItems: "unset",
                  placeSelf: "unset",
                  alignmentBaseline: "",
                  anchorName: "",
                  anchorScope: "",
                  animationComposition: "",
                  animation: "unset",
                  appRegion: "",
                  aspectRatio: "",
                  backdropFilter: "",
                  backfaceVisibility: "",
                  background: "unset",
                  backgroundBlendMode: "",
                  baselineShift: "",
                  baselineSource: "",
                  blockSize: "",
                  borderBlock: "unset",
                  border: "unset",
                  borderRadius: "unset",
                  borderCollapse: "",
                  borderEndEndRadius: "",
                  borderEndStartRadius: "",
                  borderInline: "unset",
                  borderStartEndRadius: "",
                  borderStartStartRadius: "",
                  inset: "unset",
                  boxDecorationBreak: "",
                  boxShadow: "",
                  boxSizing: "",
                  breakAfter: "",
                  breakBefore: "",
                  breakInside: "",
                  bufferedRendering: "",
                  captionSide: "",
                  caretColor: "",
                  clear: "",
                  clip: "",
                  clipPath: "",
                  clipRule: "",
                  colorInterpolation: "",
                  colorInterpolationFilters: "",
                  colorRendering: "",
                  columns: "unset",
                  columnFill: "",
                  gap: "unset",
                  columnRule: "unset",
                  columnSpan: "",
                  contain: "",
                  containIntrinsicBlockSize: "",
                  containIntrinsicSize: "unset",
                  containIntrinsicInlineSize: "",
                  container: "unset",
                  content: "",
                  contentVisibility: "",
                  counterIncrement: "",
                  counterReset: "",
                  counterSet: "",
                  cursor: "",
                  cx: "",
                  cy: "",
                  d: "",
                  dominantBaseline: "",
                  emptyCells: "",
                  fieldSizing: "",
                  fill: "",
                  fillOpacity: null,
                  fillRule: "",
                  filter: "",
                  flex: "unset",
                  flexFlow: "unset",
                  cssFloat: "",
                  floodColor: "",
                  floodOpacity: "",
                  grid: "unset",
                  gridArea: "unset",
                  height: "",
                  hyphenateCharacter: "",
                  hyphenateLimitChars: "",
                  hyphens: "",
                  imageOrientation: "",
                  imageRendering: "",
                  initialLetter: "",
                  inlineSize: "",
                  insetBlock: "unset",
                  insetInline: "unset",
                  interpolateSize: "",
                  isolation: "",
                  letterSpacing: "",
                  lightingColor: "",
                  lineBreak: "",
                  listStyle: "unset",
                  marginBlock: "unset",
                  margin: "unset",
                  marginInline: "unset",
                  marker: "unset",
                  maskType: "",
                  mathShift: "",
                  mathStyle: "",
                  maxBlockSize: "",
                  maxHeight: "",
                  maxInlineSize: "",
                  maxWidth: "",
                  minBlockSize: "",
                  minHeight: "",
                  minInlineSize: "",
                  minWidth: "",
                  mixBlendMode: "",
                  objectFit: "",
                  objectPosition: "",
                  objectViewBox: "",
                  offset: "unset",
                  opacity: null,
                  order: null,
                  orphans: null,
                  outline: "unset",
                  outlineOffset: "",
                  overflowAnchor: "",
                  overflowClipMargin: "",
                  overflowWrap: "",
                  overflow: "unset",
                  overlay: "",
                  overscrollBehaviorBlock: "",
                  overscrollBehaviorInline: "",
                  overscrollBehavior: "unset",
                  paddingBlock: "unset",
                  paddingInline: "unset",
                  page: "",
                  pageOrientation: "",
                  paintOrder: "",
                  perspective: "",
                  perspectiveOrigin: "",
                  pointerEvents: "",
                  positionTry: "unset",
                  positionVisibility: "",
                  quotes: "",
                  r: "",
                  resize: "",
                  rotate: "",
                  rubyAlign: "",
                  rubyPosition: "",
                  rx: "",
                  ry: "",
                  scale: "",
                  scrollBehavior: "",
                  scrollMarginBlock: "unset",
                  scrollMargin: "unset",
                  scrollMarginInline: "unset",
                  scrollPaddingBlock: "unset",
                  scrollPadding: "unset",
                  scrollPaddingInline: "unset",
                  scrollSnapAlign: "",
                  scrollSnapStop: "",
                  scrollSnapType: "",
                  scrollTimeline: "unset",
                  scrollbarColor: "",
                  scrollbarGutter: "",
                  scrollbarWidth: "",
                  shapeImageThreshold: "",
                  shapeMargin: "",
                  shapeOutside: "",
                  shapeRendering: "",
                  size: "",
                  speak: "",
                  stopColor: "",
                  stopOpacity: "",
                  stroke: "",
                  strokeDasharray: "",
                  strokeDashoffset: null,
                  strokeLinecap: "",
                  strokeLinejoin: "",
                  strokeMiterlimit: "",
                  strokeOpacity: null,
                  strokeWidth: null,
                  tabSize: null,
                  tableLayout: "",
                  textAlign: "",
                  textAlignLast: "",
                  textAnchor: "",
                  textCombineUpright: "",
                  textDecoration: "unset",
                  textDecorationSkipInk: "",
                  textEmphasis: "unset",
                  textEmphasisPosition: "",
                  textIndent: "",
                  textOverflow: "",
                  textShadow: "",
                  textTransform: "",
                  textUnderlineOffset: "",
                  textUnderlinePosition: "",
                  textWrap: "unset",
                  timelineScope: "",
                  touchAction: "",
                  transform: "",
                  transformBox: "",
                  transformOrigin: "",
                  transformStyle: "",
                  transition: "unset",
                  translate: "",
                  userSelect: "",
                  vectorEffect: "",
                  verticalAlign: "",
                  viewTimeline: "unset",
                  viewTransitionClass: "",
                  viewTransitionName: "",
                  visibility: "",
                  borderSpacing: "unset",
                  WebkitBoxAlign: "",
                  WebkitBoxDecorationBreak: "",
                  WebkitBoxDirection: "",
                  WebkitBoxFlex: "",
                  WebkitBoxOrdinalGroup: "",
                  WebkitBoxOrient: "",
                  WebkitBoxPack: "",
                  WebkitBoxReflect: "",
                  WebkitLineBreak: "",
                  WebkitLineClamp: "",
                  WebkitMaskBoxImage: "unset",
                  WebkitPrintColorAdjust: "",
                  WebkitRtlOrdering: "",
                  WebkitRubyPosition: "",
                  WebkitTapHighlightColor: "",
                  WebkitTextCombine: "",
                  WebkitTextDecorationsInEffect: "",
                  WebkitTextFillColor: "",
                  WebkitTextSecurity: "",
                  WebkitTextStroke: "unset",
                  WebkitUserDrag: "",
                  whiteSpaceCollapse: "",
                  widows: null,
                  width: "",
                  willChange: "",
                  wordBreak: "",
                  wordSpacing: "",
                  x: "",
                  y: "",
                  zIndex: null,
                  display: "none",
                  padding: "12px 4px 12px 16px",
                }}
              />
              <span
                className="btn-content"
                style={{
                  boxSizing: "inherit",
                  outline: "0px",
                  padding: "14.5px 16px",
                  backgroundColor: "rgb(104, 52, 128)",
                }}
              >
                {" "}
                Contact Us{" "}
              </span>
            </button>
          </div>
          <div
            className="img"
            style={{
              boxSizing: "inherit",
              outline: "0px",
              width: "calc(100% - 410px)",
              marginRight: "-140px",
              paddingLeft: "50px",
              marginBottom: "-2px",
            }}
          >
            <img
              className="ng-star-inserted"
              height={439}
              width={720}
              alt="Contact Us"
              src="https://d8it4huxumps7.cloudfront.net/uploads/images/contact-us/contact-image.png?d=1540x940"
              style={{
                boxSizing: "inherit",
                outline: "0px",
                width: "auto",
                height: "auto",
                display: "block",
                maxWidth: "100%",
              }}
            />
          </div>
        </div>
      </header>
      
    </>
  );
}
